describe('User flow testing', () => {
  
  it('should be able to search save an account, view it in the saved section, then be able to remove it from saved', () => {
    cy.intercept("GET", "https://overfast-api.tekrop.fr/players/Rokit-11457/stats?gamemode=competitive&platform=pc&hero=all-heroes", {fixture: "account.json"})
    cy.visit('http://localhost:3000/account/Rokit-11457')
    cy.get('main')
      .find('button')
      .contains('Save')
      .click()
    cy.get('.header')
      .get('button').contains('Saved')
      .click()
    cy.get('main')
      .find('.saved-tile')
      .contains('Rokit#11457')
    cy.get('main')
      .find('button')
      .contains('Remove')
      .click()
    cy.get('main')
      .find('.saved-tile')
      .should('not.exist')
  })
})